# fly.toml app configuration file generated for qa-backend-faiss on 2025-07-04T09:35:24+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'qa-backend-faiss'
primary_region = 'nrt'

[build]

[env]
  HOST = '0.0.0.0'
  PORT = '8080'

[[mounts]]
  source = 'qa_data'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
